### ISSUE TITLE
add .jshintrc to spec folder

### ISSUE THREAD

**Issue by extdevelopment** [andresdominguez/generator-protractor#5]
I would like to ask, would it be possible generate .jshintrc file to spec folder

some documentation:
https://github.com/angular/protractor/blob/master/spec/.jshintrc

thx

**Comment by andresdominguez** [comment]
Thank you for the suggestion. The idea behind this generator is to get you started with protractor with the minimum amount of code and configuration. Adding a jshint file would add unnecessary noise to the generated protractor project.

**Comment by extdevelopment** [comment]
Thank you for your reply.
Your project, your call...
